import Link from 'next/link';
import { notFound,redirect } from 'next/navigation';
import { getAdminSession } from '../../../../../../lib/admin-auth';
import { getAdminTrackAnnotationImportPreview,getAdminTrackAnnotations,isAdminDatabaseConfigured } from '../../../../../../lib/admin-database';
import { applyTrackAnnotationImport,previewLegacyTrackAnnotationImport,previewTrackAnnotationImport,removeTrackAnnotation,saveTrackAnnotation,saveTrackSectorSegmentation,saveTrackStartFinish } from '../../../../../actions';
import { TrackAnnotationGeometryEditor } from './track-annotation-geometry-editor';
import { TrackAnnotationImportPreview } from './track-annotation-import-preview';
import { SectorSegmentationEditor } from './sector-segmentation-editor';
import { StartFinishEditor } from './start-finish-editor';
import { UnifiedTrackAnnotationMap } from './unified-track-annotation-map';
import { getLegacyTrackMarkup,hideTransferredLegacyMarkup } from './legacy-track-markup';

const labels:Record<string,string>={sector:'Сектор',turn:'Поворот',straight:'Прямая',timing_line:'Отсечка времени',drs_zone:'Зона DRS',drs_detection:'Детекция DRS',straight_mode_zone:'Straight Mode · участок',straight_mode_activation:'Straight Mode · активация',straight_mode_low_grip_activation:'Straight Mode · низкое сцепление',overtake_detection:'Overtake Mode · детекция',overtake_activation:'Overtake Mode · активация'};
const statusLabels:Record<string,string>={candidate:'Кандидат',reviewed:'Проверена',published:'Опубликована',hidden:'Скрыта'};
const spa2026Modes=[
  {zone:'A1',normal:'190 м после T19',low:'240 м после T19'},
  {zone:'A2',normal:'140 м после T1',low:'195 м после T1'},
  {zone:'A3',normal:'60 м после T4',low:'360 м после T4'},
  {zone:'A4',normal:'140 м после T15',low:'190 м после T15'},
  {zone:'A5',normal:'80 м после T17',low:'110 м после T17'},
];
const spa2026FiaMap='https://www.fia.com/system/files/decision-document/2026_belgian_grand_prix_-_competition_notes_-_circuit_map_pit_lane_drawing_emergency_exits_map_and_red_zone.pdf';
export default async function Page({params,searchParams}:{params:Promise<{id:string;layoutId:string}>;searchParams:Promise<{edit?:string;saved?:string;deleted?:string;error?:string;importPreview?:string;imported?:string;syncError?:string;panel?:string}>}){
  if(!await getAdminSession())redirect('/admin/login');if(!isAdminDatabaseConfigured())redirect('/admin/overview');const[{id:circuitId,layoutId},state]=await Promise.all([params,searchParams]);
  const [registry,rawImportPreview]=await Promise.all([getAdminTrackAnnotations(circuitId,layoutId).catch(()=>null),state.importPreview?getAdminTrackAnnotationImportPreview(state.importPreview).catch(()=>null):Promise.resolve(null)]);if(!registry)notFound();
  const importPreview=rawImportPreview?.circuit.id===circuitId&&rawImportPreview.layout.id===layoutId?rawImportPreview:null;const selected=state.edit?registry.annotations.find(item=>item.id===state.edit)??null:null;
  const legacyMarkup=getLegacyTrackMarkup(circuitId,layoutId);
  const visibleLegacyMarkup=legacyMarkup?hideTransferredLegacyMarkup(legacyMarkup,layoutId,new Set(registry.annotations.map(item=>item.id)),new Set(registry.annotations.filter(item=>item.sequence!==null&&item.reviewStatus!=='hidden').map(item=>`${item.annotationType}:${item.sequence}:${item.validFromYear??0}`))):null;
  const defaultFrom=selected?.validFromYear??registry.layout.validFromYear??'';const defaultTo=selected?.validToYear??registry.layout.validToYear??'';
  const finishId=`${layoutId}-start-finish`;
  const reservedFinish=registry.annotations.find(item=>item.id===finishId)??null;
  const manualFinish=reservedFinish?.annotationType==='timing_line'&&reservedFinish.geometryGeoJson.type==='Point'?reservedFinish:null;
  const firstSector=registry.annotations.filter(item=>item.annotationType==='sector'&&item.sequence===1&&item.reviewStatus!=='hidden'&&item.geometryGeoJson.type==='LineString').sort((a,b)=>(b.validFromYear??0)-(a.validFromYear??0))[0]??null;
  const autoFinish=firstSector?.geometryGeoJson.type==='LineString'?firstSector.geometryGeoJson.coordinates[0]:legacyMarkup?.trackSectors.features[0]?.geometry.coordinates[0]??registry.layout.centerlineGeoJson?.coordinates[0]??null;
  const importSection=registry.layout.centerlineGeoJson?<section id="batch-import" className="admin-related-section"><header><div><span className="admin-kicker">Пакетная разметка</span><h2>Импорт GeoJSON</h2></div></header>{importPreview?<TrackAnnotationImportPreview preview={importPreview} circuitId={circuitId} layoutId={layoutId} applyAction={applyTrackAnnotationImport}/>:<form action={previewTrackAnnotationImport} className="admin-editor-form"><input type="hidden" name="circuitId" value={circuitId}/><input type="hidden" name="layoutId" value={layoutId}/><fieldset><legend>Пакет кандидатов</legend><div className="admin-form-grid"><label className="is-wide"><span>GeoJSON FeatureCollection</span><input type="file" name="packageFile" accept=".geojson,.json,application/geo+json,application/json" required/><small>До 5 МБ. Пакет должен относиться к этой трассе и конфигурации; запись в базу начнётся только после предпросмотра</small></label></div></fieldset><div className="admin-form-actions"><span>Все элементы импортируются как кандидаты и не публикуются автоматически</span><button type="submit">Проверить пакет</button></div></form>}</section>:null;
  return <main className="admin-shell admin-track-annotations-shell"><section className="admin-edit-panel admin-track-annotations"><Link className="admin-back-link" href={`/admin/circuits/${circuitId}/layouts/${layoutId}`}>← Конфигурация</Link>
    <header><div><span className="admin-kicker">Разметка конфигурации</span><h1>{registry.layout.name}</h1><p>{registry.circuit.name} · {registry.annotations.length} {registry.annotations.length===1?'элемент':'элементов'}</p></div></header>
    {state.saved?<div className="admin-alert is-success">{state.saved==='sectors'?'Три сектора сохранены как кандидаты':'Разметка сохранена'}</div>:null}{state.deleted?<div className="admin-alert is-success">Элемент удалён</div>:null}{state.imported?<div className="admin-alert is-success">Импортировано элементов: {state.imported}</div>:null}{state.syncError?<div className="admin-alert is-error">Разметка в базе сохранена, но публичная страница не обновилась. Проверьте экспорт данных трассы</div>:null}{state.error?<div className="admin-alert is-error">{state.error==='conflict'?'Этот элемент изменился после открытия формы. Ваше действие не применено: обновите страницу и проверьте актуальную разметку':state.error==='sectors'?'Не удалось сохранить сектора. Проверьте направление оси трассы, период, источник и существующие сектора':state.error==='legacy-import'?'Не удалось подготовить перенос. Проверьте источник и убедитесь, что элементы ещё не перенесены':state.error==='import-preview'?'Не удалось проверить пакет. Проверьте формат, конфигурацию, источник и расстояние до контура':state.error==='import-apply'?'Не удалось применить пакет. Предпросмотр мог устареть или конфликтует с проверенной разметкой':'Не удалось выполнить действие. Проверьте геометрию, период, источник и уникальность номера'}</div>:null}
    {importPreview?importSection:null}
    {registry.layout.centerlineGeoJson?<UnifiedTrackAnnotationMap centerline={registry.layout.centerlineGeoJson} legacyMarkup={visibleLegacyMarkup}><nav className="admin-track-editor-nav" aria-label="Разделы редактора"><a href="#element-editor">Элемент</a><a href="#sector-editor">Сектора</a><a href="#batch-import">Импорт</a></nav><details className="admin-track-existing-list"><summary>Сохранённые элементы · {registry.annotations.length}</summary><ul>{registry.annotations.map(item=><li key={item.id}><Link scroll={false} href={`?edit=${encodeURIComponent(item.id)}`}>{item.sequence?`${item.sequence} · `:''}{item.labelRu??item.labelOriginal??labels[item.annotationType]}<span>{statusLabels[item.reviewStatus]}</span></Link></li>)}</ul></details>{legacyMarkup?<section className="admin-related-section"><header><div><span className="admin-kicker">Существующая разметка</span><h2>Перенести в кандидаты</h2></div></header><p>Публичная карта содержит {legacyMarkup.trackSectors.features.length} сектора, {legacyMarkup.turnLabels.features.length} номеров поворотов и {legacyMarkup.drsZones.features.length} зоны DRS. На рабочей карте перенесённые элементы показываются как редактируемые записи, остальные — как справочный слой. Укажите схему-источник и проверьте пакет перед переносом. Названия групп поворотов и прямых остаются справочными: их тип и протяжённость нужно подтвердить отдельно</p><form action={previewLegacyTrackAnnotationImport} className="admin-editor-form"><input type="hidden" name="circuitId" value={circuitId}/><input type="hidden" name="layoutId" value={layoutId}/><div className="admin-form-grid"><label><span>Название источника</span><input name="sourceName" required/></label><label className="is-wide"><span>URL схемы</span><input name="sourceUrl" type="url" required placeholder="https://…"/></label><label className="admin-rights-confirmation"><input type="checkbox" name="sourceAcknowledged" value="yes" required/><span><strong>Источник относится к этой конфигурации</strong><small>Все элементы будут кандидатами и не появятся автоматически на публичной карте</small></span></label></div><div className="admin-form-actions"><span>Уже перенесённые записи не будут заменены</span><button type="submit">Предпросмотр переноса</button></div></form></section>:null}<section id="sector-editor" className="admin-related-section"><header><div><span className="admin-kicker">Сектора круга</span><h2>Разделить по двум границам</h2></div></header>
      <form id="sector-segmentation-form" action={saveTrackSectorSegmentation} className="admin-editor-form"><input type="hidden" name="circuitId" value={circuitId}/><input type="hidden" name="layoutId" value={layoutId}/>
        <SectorSegmentationEditor centerline={registry.layout.centerlineGeoJson}/>
        <fieldset><legend>Период и источник</legend><div className="admin-form-grid">
          <label><span>Действует с года</span><input name="validFromYear" type="number" min="1900" max="2100" defaultValue={registry.layout.validFromYear??''}/></label>
          <label><span>Действует до года</span><input name="validToYear" type="number" min="1900" max="2100" defaultValue={registry.layout.validToYear??''}/></label>
          <label><span>Название источника</span><input name="sourceName"/></label>
          <label className="is-wide"><span>URL схемы секторов</span><input name="sourceUrl" type="url" required placeholder="https://…"/></label>
          <label className="is-wide"><span>Что подтверждает источник</span><textarea name="sourceNotes" rows={2}/></label>
        </div></fieldset>
        <div className="admin-form-actions"><span>Положение старта/финиша и направление круга сверьте со схемой из источника. Сектора сохраняются кандидатами и не заменяют существующую разметку периода</span></div>
      </form></section>
    {reservedFinish&&!manualFinish?<div className="admin-alert is-error">ID старта/финиша занят другим элементом. Проверьте запись в списке сохранённых элементов; быстрое сохранение недоступно, чтобы не заменить её</div>:<StartFinishEditor centerline={registry.layout.centerlineGeoJson} autoPoint={autoFinish??registry.layout.centerlineGeoJson.coordinates[0]} manual={manualFinish} circuitId={circuitId} layoutId={layoutId} validFromYear={registry.layout.validFromYear} validToYear={registry.layout.validToYear} action={saveTrackStartFinish}/>}
    {circuitId==='spa'&&layoutId==='be-1925'?<section className="admin-related-section"><header><div><span className="admin-kicker">Спа · этап 2026</span><h2>Straight Mode и Overtake Mode</h2></div></header><p>Это справочные ориентиры для ручного нанесения на существующий контур, не готовые координаты. Создайте пять участков Straight Mode и отметьте активацию для обычного и низкого сцепления. Overtake Mode — отдельная система: точка детекции на входе в T19, активация через 130 м после T19. Перенесённые зоны DRS относятся только к 2025 году</p><div className="admin-table-wrap"><table><thead><tr><th>Зона</th><th>Обычное сцепление · активация</th><th>Низкое сцепление · активация</th></tr></thead><tbody>{spa2026Modes.map(item=><tr key={item.zone}><td>{item.zone}</td><td>{item.normal}</td><td>{item.low}</td></tr>)}</tbody></table></div><p><a href={spa2026FiaMap} target="_blank" rel="noreferrer">Официальная карта FIA, документ 7 от 16.07.2026 ↗</a>. Для каждого нового элемента укажите начало и конец действия 2026, источник и статус «Кандидат». Геометрию сверяйте вручную: FIA не публикует её в GeoJSON</p></section>:null}
    <form id="element-editor" action={saveTrackAnnotation} className="admin-editor-form"><input type="hidden" name="circuitId" value={circuitId}/><input type="hidden" name="layoutId" value={layoutId}/>{selected?<input type="hidden" name="revision" value={selected.revision}/>:null}
      <fieldset><legend>{selected?'Редактирование элемента':'Новый элемент'}</legend><TrackAnnotationGeometryEditor key={selected?.id??'new'} centerline={registry.layout.centerlineGeoJson} annotations={registry.annotations} selected={selected}/><div className="admin-form-grid"><label><span>ID</span>{selected?<><input type="hidden" name="annotationId" value={selected.id}/><input value={selected.id} disabled/></>:<><input name="annotationId" pattern="[A-Za-z0-9_-]+" placeholder="Создастся автоматически"/><small>Заполняйте только если нужен собственный ID</small></>}</label><label className="is-wide"><span>Описание</span><textarea name="descriptionRu" rows={3} defaultValue={selected?.descriptionRu??''}/></label></div></fieldset>
      <fieldset><legend>Период и проверка</legend><div className="admin-form-grid"><label><span>Действует с года</span><input name="validFromYear" type="number" min="1900" max="2100" defaultValue={defaultFrom}/></label><label><span>Действует до года</span><input name="validToYear" type="number" min="1900" max="2100" defaultValue={defaultTo}/></label><label><span>Статус</span><select name="reviewStatus" defaultValue={selected?.reviewStatus??'candidate'}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Название источника</span><input name="sourceName" defaultValue={selected?.sourceName??''}/></label><label className="is-wide"><span>URL источника</span><input name="sourceUrl" type="url" defaultValue={selected?.sourceUrl??''} required placeholder="https://…"/></label><label className="is-wide"><span>Что подтверждает источник</span><textarea name="sourceNotes" rows={2} defaultValue={selected?.sourceNotes??''}/></label><label className="admin-rights-confirmation"><input type="checkbox" name="sourceVerified" value="yes"/><span><strong>Источник проверен</strong><small>Обязательно для статусов «Проверена» и «Опубликована». При изменении источника подтвердите его повторно</small></span></label></div></fieldset>
      <div className="admin-form-actions"><span>Точки разметки должны находиться не дальше 2 км от контура</span><button type="submit">Сохранить как {selected?'изменение':'новый элемент'}</button></div></form></UnifiedTrackAnnotationMap>:<div className="admin-alert is-error">Сначала загрузите контур конфигурации. Разметка без базовой линии не создаётся</div>}
    {!importPreview?importSection:null}
    <section className="admin-related-section"><header><div><span className="admin-kicker">Сохранённая разметка</span><h2>Элементы</h2></div></header><div className="admin-table-wrap"><table><thead><tr><th>Тип</th><th>Номер и название</th><th>Период</th><th>Статус</th><th>Источник</th><th/></tr></thead><tbody>{registry.annotations.map(item=><tr key={item.id}><td>{labels[item.annotationType]??item.annotationType}</td><td><strong>{item.sequence?`${item.sequence} · `:''}{item.labelRu??item.labelOriginal}</strong><small>{item.id}</small></td><td>{item.validFromYear??'…'}–{item.validToYear??'н.в.'}</td><td><span className={`admin-status is-${item.reviewStatus}`}>{statusLabels[item.reviewStatus]}</span></td><td>{item.sourceUrl?<a href={item.sourceUrl} target="_blank" rel="noreferrer">Открыть ↗</a>:'—'}</td><td><Link className="admin-row-action" href={`?edit=${encodeURIComponent(item.id)}`}>Редактировать →</Link></td></tr>)}</tbody></table></div>{!registry.annotations.length?<p className="admin-directory-empty">Разметка ещё не добавлена</p>:null}</section>
    {selected?<form action={removeTrackAnnotation} className="admin-delete-panel"><input type="hidden" name="circuitId" value={circuitId}/><input type="hidden" name="layoutId" value={layoutId}/><input type="hidden" name="annotationId" value={selected.id}/><input type="hidden" name="revision" value={selected.revision}/><label><input type="checkbox" name="confirmed" value="yes" required/> Подтверждаю удаление элемента {selected.id}</label><button type="submit">Удалить элемент</button></form>:null}
  </section></main>;
}
