import Link from 'next/link';
import { notFound,redirect } from 'next/navigation';
import { getAdminSession } from '../../../../../../lib/admin-auth';
import { getAdminTrackAnnotationImportPreview,getAdminTrackAnnotations,isAdminDatabaseConfigured } from '../../../../../../lib/admin-database';
import { applyTrackAnnotationImport,previewTrackAnnotationImport,removeTrackAnnotation,saveTrackAnnotation } from '../../../../../actions';
import { TrackAnnotationGeometryEditor } from './track-annotation-geometry-editor';
import { TrackAnnotationImportPreview } from './track-annotation-import-preview';

const labels:Record<string,string>={sector:'Сектор',turn:'Поворот',straight:'Прямая',timing_line:'Отсечка времени',drs_zone:'Зона DRS',drs_detection:'Детекция DRS'};
const statusLabels:Record<string,string>={candidate:'Кандидат',reviewed:'Проверена',published:'Опубликована',hidden:'Скрыта'};
export default async function Page({params,searchParams}:{params:Promise<{id:string;layoutId:string}>;searchParams:Promise<{edit?:string;saved?:string;deleted?:string;error?:string;importPreview?:string;imported?:string}>}){
  if(!await getAdminSession())redirect('/admin/login');if(!isAdminDatabaseConfigured())redirect('/admin/overview');const[{id:circuitId,layoutId},state]=await Promise.all([params,searchParams]);
  const [registry,rawImportPreview]=await Promise.all([getAdminTrackAnnotations(circuitId,layoutId).catch(()=>null),state.importPreview?getAdminTrackAnnotationImportPreview(state.importPreview).catch(()=>null):Promise.resolve(null)]);if(!registry)notFound();
  const importPreview=rawImportPreview?.circuit.id===circuitId&&rawImportPreview.layout.id===layoutId?rawImportPreview:null;const selected=state.edit?registry.annotations.find(item=>item.id===state.edit)??null:null;
  const defaultFrom=selected?.validFromYear??registry.layout.validFromYear??'';const defaultTo=selected?.validToYear??registry.layout.validToYear??'';
  return <main className="admin-shell"><section className="admin-edit-panel admin-track-annotations"><Link className="admin-back-link" href={`/admin/circuits/${circuitId}/layouts/${layoutId}`}>← Конфигурация</Link>
    <header><div><span className="admin-kicker">Разметка конфигурации</span><h1>{registry.layout.name}</h1><p>{registry.circuit.name} · {registry.annotations.length} элементов</p></div><Link className="admin-row-action" href={`/admin/circuits/${circuitId}/layouts/${layoutId}/annotations`}>Добавить элемент</Link></header>
    {state.saved?<div className="admin-alert is-success">Разметка сохранена</div>:null}{state.deleted?<div className="admin-alert is-success">Элемент удалён</div>:null}{state.imported?<div className="admin-alert is-success">Импортировано элементов: {state.imported}</div>:null}{state.error?<div className="admin-alert is-error">{state.error==='import-preview'?'Не удалось проверить пакет. Проверьте формат, конфигурацию, источник и расстояние до контура':state.error==='import-apply'?'Не удалось применить пакет. Предпросмотр мог устареть или конфликтует с проверенной разметкой':'Не удалось выполнить действие. Проверьте геометрию, период, источник и уникальность номера'}</div>:null}
    {registry.layout.centerlineGeoJson?<section className="admin-related-section"><header><div><span className="admin-kicker">Пакетная разметка</span><h2>Импорт GeoJSON</h2></div></header>{importPreview?<TrackAnnotationImportPreview preview={importPreview} circuitId={circuitId} layoutId={layoutId} applyAction={applyTrackAnnotationImport}/>:<form action={previewTrackAnnotationImport} className="admin-editor-form"><input type="hidden" name="circuitId" value={circuitId}/><input type="hidden" name="layoutId" value={layoutId}/><fieldset><legend>Пакет кандидатов</legend><div className="admin-form-grid"><label className="is-wide"><span>GeoJSON FeatureCollection</span><input type="file" name="packageFile" accept=".geojson,.json,application/geo+json,application/json" required/><small>До 5 МБ. Пакет должен относиться к этой трассе и конфигурации; запись в базу начнётся только после предпросмотра</small></label></div></fieldset><div className="admin-form-actions"><span>Все элементы импортируются как кандидаты и не публикуются автоматически</span><button type="submit">Проверить пакет</button></div></form>}</section>:null}
    {!registry.layout.centerlineGeoJson?<div className="admin-alert is-error">Сначала загрузите контур конфигурации. Разметка без базовой линии не создаётся</div>:<form action={saveTrackAnnotation} className="admin-editor-form"><input type="hidden" name="circuitId" value={circuitId}/><input type="hidden" name="layoutId" value={layoutId}/>
      <fieldset><legend>{selected?'Редактирование элемента':'Новый элемент'}</legend><div className="admin-form-grid"><label><span>ID</span>{selected?<><input type="hidden" name="annotationId" value={selected.id}/><input value={selected.id} disabled/></>:<input name="annotationId" pattern="[A-Za-z0-9_-]+" placeholder={`${layoutId}-turn-01`} required/>}</label><label><span>Номер</span><input name="sequence" type="number" min="1" max="999" defaultValue={selected?.sequence??''}/></label><label><span>Название на русском</span><input name="labelRu" defaultValue={selected?.labelRu??''} placeholder="Eau Rouge"/></label><label><span>Оригинальное название</span><input name="labelOriginal" defaultValue={selected?.labelOriginal??''}/></label><label className="is-wide"><span>Описание</span><textarea name="descriptionRu" rows={3} defaultValue={selected?.descriptionRu??''}/></label></div>
      <TrackAnnotationGeometryEditor centerline={registry.layout.centerlineGeoJson} annotations={registry.annotations} selected={selected}/></fieldset>
      <fieldset><legend>Период и проверка</legend><div className="admin-form-grid"><label><span>Действует с года</span><input name="validFromYear" type="number" min="1900" max="2100" defaultValue={defaultFrom}/></label><label><span>Действует до года</span><input name="validToYear" type="number" min="1900" max="2100" defaultValue={defaultTo}/></label><label><span>Статус</span><select name="reviewStatus" defaultValue={selected?.reviewStatus??'candidate'}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Название источника</span><input name="sourceName" defaultValue={selected?.sourceName??''}/></label><label className="is-wide"><span>URL источника</span><input name="sourceUrl" type="url" defaultValue={selected?.sourceUrl??''} required placeholder="https://…"/></label><label className="is-wide"><span>Что подтверждает источник</span><textarea name="sourceNotes" rows={2}/></label><label className="admin-rights-confirmation"><input type="checkbox" name="sourceVerified" value="yes"/><span><strong>Источник проверен</strong><small>Обязательно для статусов «Проверена» и «Опубликована»</small></span></label></div></fieldset>
      <div className="admin-form-actions"><span>Точки разметки должны находиться не дальше 2 км от контура</span><button type="submit">Сохранить как {selected?'изменение':'новый элемент'}</button></div></form>}
    <section className="admin-related-section"><header><div><span className="admin-kicker">Сохранённая разметка</span><h2>Элементы</h2></div></header><div className="admin-table-wrap"><table><thead><tr><th>Тип</th><th>Номер и название</th><th>Период</th><th>Статус</th><th>Источник</th><th/></tr></thead><tbody>{registry.annotations.map(item=><tr key={item.id}><td>{labels[item.annotationType]??item.annotationType}</td><td><strong>{item.sequence?`${item.sequence} · `:''}{item.labelRu??item.labelOriginal}</strong><small>{item.id}</small></td><td>{item.validFromYear??'…'}–{item.validToYear??'н.в.'}</td><td><span className={`admin-status is-${item.reviewStatus}`}>{statusLabels[item.reviewStatus]}</span></td><td>{item.sourceUrl?<a href={item.sourceUrl} target="_blank" rel="noreferrer">Открыть ↗</a>:'—'}</td><td><Link className="admin-row-action" href={`?edit=${encodeURIComponent(item.id)}`}>Редактировать →</Link></td></tr>)}</tbody></table></div>{!registry.annotations.length?<p className="admin-directory-empty">Разметка ещё не добавлена</p>:null}</section>
    {selected?<form action={removeTrackAnnotation} className="admin-delete-panel"><input type="hidden" name="circuitId" value={circuitId}/><input type="hidden" name="layoutId" value={layoutId}/><input type="hidden" name="annotationId" value={selected.id}/><label><input type="checkbox" name="confirmed" value="yes" required/> Подтверждаю удаление элемента {selected.id}</label><button type="submit">Удалить элемент</button></form>:null}
  </section></main>;
}
